name: CarpetPlugin
version: '${version}'
main: esuny.carpetplugin.CarpetPlugin
api-version: 1.18
description: 实现CarpetMod部分功能&Partital implementation of Carpet Mod
permissions:
  carpet.player:
    description: "Access to player command"
    default: true
    children:
      - "carpet.player.spawn"
      - "carpet.player.kill"
      - "minecraft.command.player"
      - "carpet.player.sneak"
      - "carpet.player.stop"
      - "carpet.player.actions"
      - "carpet.player.look"
  carpet.player.spawn:
    description: "Allow spawning fake players"
    default: true
  carpet.player.spawn.whitelist:
    description: "Allow spawning fake whitelisted players"
    default: false
  carpet.player.spawn.sync:
    description: "Allow spawning fake players synchronized"
  carpet.player.kill:
    description: "Allow killing fake players"
    default: true
  carpet.player.sneak:
    description: "Allow sneaking fake players"
    default: true
  carpet.player.stop:
    description: "Allow stopping fake players"
    default: true
  carpet.player.actions:
    description: "Allow getting fake players current active actions"
    default: true
  carpet.player.look:
    description: "让假人看向某处"
    default: true
commands:
  spawn:
    aliases:
      - "sp"
    usage: "/sp <玩家名字>"
    description: "生成一个假人"
    permission: "carpet.player.spawn"
    permission-message: "§c您无权执行此操作You don't have the permission to perform this action"